spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sg-videofactory-prod.cluster-coavkbixiaz8.ap-southeast-1.rds.amazonaws.com:3306/cgtn-video?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: shenzhoushumaprod
    password: GAHb^Ca4YdpJ

eureka:
  client:
    service-url:
      defaultZone: http://192.168.8.36:8008/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
knife4j:
  enable: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cgtn.workshop.socialplatform
  default-flat-param-object: false

logging:
  level:
    com.netflix: warn

social:
  facebook:
#    client-id: '1032314974648862'
#    client-secret: '31ef5ba83d41d859d880a230114ddcdf'
    client-id: '389235610578412'
    client-secret: '43e0aae28d6c5bbce860e22e601a73b3'
    redirect-uri: 'https://platform.ivideofactory.com/social-platform/facebook/callback'
  twitter:
#    client-id: 'TVhhWWg4ZTJXWlBFWUJWWDIyTkk6MTpjaQ'
#    client-secret: 'TJ3h5qv5OgDAA77NXa0xlNZO8yzFuc1MCwF2kHWDpzhebWEatF'
    client-id: 'bGZrSnhjaW5vLXNGdHNWcE5LTGQ6MTpjaQ'
    client-secret: 'bJO8HolnH6uy0GMomH05wRG8ZWYq6e4O6ykSkSWuW3gYsATZHd'
    consumer-key: 'KVdrFJTULRJL8hoVmooztMEfE'
    consumer-secret: 'VFMEU1aT4F1WPMjzeMtcAaKHomxtky3ifcF6RColF78d9wSjWX'
    access-token: '1729739373888110592-ngbV1OvF7NuOGP9UszUjxSrOu0WDJ9'
    access-token-secret: '2IgpsekpOQedu3daMx4jZvR3qvyf1qwNoVn905vkuIruV'
    redirect-uri: 'https://platform.ivideofactory.com/social-platform/twitter/callback'
  tiktok:
#    client-key: 'awihm0gdoh7bofjy'
#    client-secret: '9xDHSIMNjhbBpVy6LcfAXMxNY5vVwM4y'
    client-key: 'awe30ze4vt03fe5s'
    client-secret: 'Ce0Lcb6y0m8cmVZwa5OHwTSdUUBmm1r4'
    redirect-uri: 'https://platform.ivideofactory.com/social-platform/tiktok/callback'
    privacy-level: 'SELF_ONLY'
  youtube:
#    client-id: '76123728679-i3k84c7n32oin9hiobqlphh0m4l19ips.apps.googleusercontent.com'
#    client-secret: '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'
    client-id: '955798060872-ogp5q09v2qd9oson0r8n0gt1pn8uqo4e.apps.googleusercontent.com'
    client-secret: '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'
#    client-id: '364810997726-5jfc47trq6nieg25npb5ef34deshmgn7.apps.googleusercontent.com'
#    client-secret: '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'
    auth-uri: "https://accounts.google.com/o/oauth2/auth"
    token-uri: "https://oauth2.googleapis.com/token"
    redirect-uri: 'https://platform.ivideofactory.com/social-platform/youtube/callback'
