spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sg-videofactory-test.coavkbixiaz8.ap-southeast-1.rds.amazonaws.com:3306/cgtn-video?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: shenzhoushumatest
    password: RpRC59#8$SKQ!
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB 
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8008/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh
        
knife4j:
  enable: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cgtn.workshop.videocreation
  default-flat-param-object: false
 
aws-customized-platform:
  host: https://cb3lmjfew4.execute-api.us-east-1.amazonaws.com/prod
  model-id: anthropic.claude-3-sonnet-20240229-v1:0
  api-key: miRtacjTvE7mijZjDTUs36AeSLMNZAs14yvE4Ay9
aws:
  s3:
    bucket: sg-videofactory-test
    region: ap-southeast-1
    crop-folder: shenzhoushuma/crop/
  slice-s3:
    bucket: ai-video-editing-637423353769-us-east-1-bucket
    region: us-east-1
    upload-folder: upload/
aes:
  key: c57e4b6ea64debc7
  iv: a97a26054868a3f7
file:
  temp:
    path: /videofactory/temp/
